language: java
dist: xenial
jdk:
  - oraclejdk11
  - openjdk11
  - oraclejdk16
  - openjdk16
notifications:
  email: false
addons:
  apt:
    packages:
      - sshpass
script: mvn clean install
after_success:
- ./travis-upload.sh
